name: build

on:
  push:
    branches: [ "dev", "gl" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        msystem: [ MINGW64, MINGW32, CLANG64 ]
    name: ${{ matrix.msystem }}
    runs-on: windows-2019
    env:
      MSYSTEM: ${{ matrix.msystem }}
    defaults:
      run:
        shell: C:\shells\msys2bash.cmd {0}
    steps:
    - name: Disable autocrlf
      shell: bash
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Install dependency
      run: |
        pacman -S --needed --noconfirm --noprogressbar \
          ${MINGW_PACKAGE_PREFIX}-make \
          ${MINGW_PACKAGE_PREFIX}-autotools \
          ${MINGW_PACKAGE_PREFIX}-cmake \
          ${MINGW_PACKAGE_PREFIX}-ninja \
          ${MINGW_PACKAGE_PREFIX}-meson \
          ${MINGW_PACKAGE_PREFIX}-lua51 \
          ${MINGW_PACKAGE_PREFIX}-angleproject \
          ${MINGW_PACKAGE_PREFIX}-cc patch p7zip

        rm -f ${MINGW_PREFIX}/lib/liblua5.1.dll.a  
    - name: Build packages
      run: |
        for p in curl libwebp freetype harfbuzz libass ffmpeg spirv-cross shaderc mpv; do
          echo building $p
          cd $p; makepkg-mingw -sciCf --noconfirm; cd ..
        done

        cd ${MINGW_PREFIX}
        7z a -mx=9 ${GITHUB_WORKSPACE}/mpv-dev-${MSYSTEM_CARCH}.7z include/mpv \
          ${MINGW_PREFIX}/bin/libmpv-2.dll \
          ${MINGW_PREFIX}/lib/libmpv.dll.a \
          ${MINGW_PREFIX}/share/doc/mpv/mpv.def

    - name: Upload packages
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ matrix.msystem }}
        tag_name: ${{ matrix.msystem }}
        prerelease: true
        files: |
          */*.pkg.tar.zst
          mpv-*.7z
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/${{ matrix.msystem }}/total?label=Downloads)