name: build

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        msystem: [ MINGW64, MINGW32, CLANG64 ]
    name: ${{ matrix.msystem }}
    runs-on: windows-2019
    env:
      MSYSTEM: ${{ matrix.msystem }}
    defaults:
      run:
        shell: C:\shells\msys2bash.cmd {0}
    steps:
    - name: Disable autocrlf
      shell: bash
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Install dependency
      run: |
        pacman -S --needed --noconfirm --noprogressbar \
          ${MINGW_PACKAGE_PREFIX}-make \
          ${MINGW_PACKAGE_PREFIX}-autotools \
          ${MINGW_PACKAGE_PREFIX}-cmake \
          ${MINGW_PACKAGE_PREFIX}-ninja \
          ${MINGW_PACKAGE_PREFIX}-meson \
          ${MINGW_PACKAGE_PREFIX}-cc patch
    - name: Build packages
      run: |
        for p in curl libwebp freetype harfbuzz libass ffmpeg mpv; do
          echo building $p
          cd $p; makepkg-mingw -sciCf --noconfirm; cd ..
        done
    - name: Upload packages
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ matrix.msystem }}
        tag_name: ${{ matrix.msystem }}
        prerelease: true
        files: |
          mpv/*.pkg.tar.zst
          curl/*.pkg.tar.zst
          libwebp/*.pkg.tar.zst
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/${{ matrix.msystem }}/total?label=Downloads)